#!/bin/bash
#
####################################################################################################
Disclaimer="This script is provided on an AS IS basis."
####################################################################################################
ReadMe="Welcome to the macOS Security Compliance Project (mSCP) Admin Setup Utility. This utility is designed to lower the bar for mSCP installation and usage.

IT IS HIGHLY RECOMMENDED TO REVIEW THE PROJECT WIKI BEFORE PROCEEDING.
https://github.com/usnistgov/macos_security/wiki

TEST IN A DEVELOPMENT ENVIRONMENT FIRST

NOTE: Using the compliance scripts generated by the mSCP to fix (remediate) can make changes (by design) to a Mac system that may seriously restrict capabilities (such as login) if certain policies are not met.

Usage: This interactive utility will walk you through installing the mSCP, and generating and customizing guidance from supported baselines.

Installation:
 - Xcode Command Line Tools (for git and Python3)
 - mSCP GIT repository
 - Python and Ruby dependencies

The following output will be generated:
 - Security Baseline Documentation
 - Auditor Guide
 - mobileconfig files and plists
 - xml for extension attributes
 - shell scripts for custom attributes
 - Baseline compliance (and remediation) script"

####################################################################################################
#
# ABOUT THIS PROGRAM
#
# NAME
#
#	mSCP_Admin_Setup_Utility.sh
#
####################################################################################################
#
# DEFINE VARIABLES & READ IN PARAMETERS
#
####################################################################################################

# HARDCODED VALUES ARE SET HERE

CurrentDay=$(/bin/date "+%Y-%m-%d")
timeStamp=$(/bin/date "+%Y-%m-%d_%H-%M")
tmpFile="/tmp/.mss""${timeStamp}"

# macOS version
sw_vers_Full=$(/usr/bin/sw_vers -productVersion)
sw_build=$(/usr/bin/sw_vers -buildVersion | /usr/bin/cut -c 1-2)
macOSName=$(/usr/bin/awk '/SOFTWARE LICENSE AGREEMENT FOR macOS/' '/System/Library/CoreServices/Setup Assistant.app/Contents/Resources/en.lproj/OSXSoftwareLicense.rtf' | /usr/bin/awk -F 'macOS ' '{print $NF}' | /usr/bin/tr -d '\\')

currentUser=$(/bin/echo 'show State:/Users/ConsoleUser' | /usr/sbin/scutil | /usr/bin/awk '/Name / { print $3 }')
currentUserFullName=$(/bin/echo 'show State:/Users/ConsoleUser' | /usr/sbin/scutil | /usr/bin/awk -F ' : ' '/kCGSessionLongUserNameKey / { print $NF }')
currentUserUID=$(/usr/bin/id -u "${currentUser}")
currentUserNFSHomeDirectory=$(/usr/bin/dscl . read /Users/${currentUser} NFSHomeDirectory | /usr/bin/awk '{ print $2 }')
computerName=$(/usr/sbin/scutil --get ComputerName)

mSCP_wiki_URL="https://github.com/usnistgov/macos_security/wiki"
mSCP_github_URL="https://github.com/usnistgov/macos_security.git"

Shell_Script_Name="$(/usr/bin/basename "${0}")"
# /bin/echo "Shell_Script_Name $Shell_Script_Name"
Shell_Script_Path="${0}"
# /bin/echo "Shell_Script_Path $Shell_Script_Path"
Shell_Script_Dir="$(/usr/bin/dirname "${0}")"
# /bin/echo "Shell_Script_Dir $Shell_Script_Dir"
app_Path="$(/usr/bin/dirname "$(/usr/bin/dirname "$(/usr/bin/dirname "${Shell_Script_Path}")")")"
# /bin/echo "app_Path $app_Path"
app_Name="$(/usr/bin/basename "${app_Path}")"
# /bin/echo "app_Name $app_Name"
Contents_Path="$(/usr/bin/dirname "$(/usr/bin/dirname "${Shell_Script_Path}")")"
# /bin/echo "Contents_Path $Contents_Path"
app_Info_plist_Path="$(/usr/bin/dirname "$(/usr/bin/dirname "${Shell_Script_Path}")")/Info.plist"
# /bin/echo "app_Info_plist_Path $app_Info_plist_Path"
CFBundleShortVersionString="$(/usr/bin/defaults read "${app_Info_plist_Path}" CFBundleShortVersionString 2> /dev/null)"
# /bin/echo "CFBundleShortVersionString $CFBundleShortVersionString"
CFBundleIdentifier="$(/usr/bin/defaults read "${app_Info_plist_Path}" CFBundleIdentifier 2> /dev/null)"
# /bin/echo "CFBundleIdentifier $CFBundleIdentifier"
Last_Agreement_CFBundleShortVersionString="$(/usr/bin/defaults read ${CFBundleIdentifier} Last_Agreement_CFBundleShortVersionString 2> /dev/null)"
# /bin/echo "Last_Agreement_CFBundleShortVersionString $Last_Agreement_CFBundleShortVersionString"
SoftwareUpdate_Deferred_Date="$(/usr/bin/defaults read ${CFBundleIdentifier} SoftwareUpdate_Deferred_Date 2> /dev/null)"
# /bin/echo "SoftwareUpdate_Deferred_Date $SoftwareUpdate_Deferred_Date"
#
####################################################################################################
#
# Functions to call on
#
####################################################################################################

#
### Validate current user is an admin ###
function Open_app () {
# /bin/echo "${FUNCNAME[0]}"
if [[ "${app_Name}" == *".app" ]] ; then
	# /bin/echo "Opening ${app_Name}"
	/usr/bin/open "${app_Path}" 2> /dev/null
fi
# /bin/echo "End ${FUNCNAME[0]}"
}
###
#

#
### Validate current user is an admin ###
function admincheck () {
# /bin/echo "${FUNCNAME[0]}"
if [[ $(/usr/bin/id ${currentUser}) != *"80(admin)"* ]] ; then
	/usr/bin/clear
	/usr/bin/printf "REFRESH\n"
	DisplayDialogMessage="The mSCP Admin Setup Utility must be run from an admin account. ${currentUser} is not an admin user."
	Open_app
	/bin/echo "${DisplayDialogMessage}"
	title="macOS Security Compliance Project"
	button1="Quit"
	DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"}")
	Quit_Project
fi
# /bin/echo "End ${FUNCNAME[0]}"
}
###
#

#
### Validate current terminal user is the current console user ###
function usercheck () {
# /bin/echo "${FUNCNAME[0]}"
if [[ "${currentUserNFSHomeDirectory}" != "$HOME" ]] ; then
	/bin/echo "This script must be run as ${currentUser}"
	Quit_Project
fi
# /bin/echo "End ${FUNCNAME[0]}"
}
###
#

#
### Get User Password ###
function Get_UserPassword () {
/bin/echo "${FUNCNAME[0]}"
Open_app
DisplayDialogMessage="Your admin password is required for this process:"
/bin/echo "${DisplayDialogMessage}"
title="Password"
icon="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/FileVaultIcon.icns"
if [[ -e ${icon} ]] ; then
	UserPassword=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" default answer \"\" with hidden answer with title \"${title}\" with icon POSIX file \"${icon}\"" -e "return text returned of result")
else
	UserPassword=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" default answer \"\" with hidden answer with title \"${title}\"" -e "return text returned of result")
fi

if [ $? -eq 1 ]; then
	/bin/echo "User canceled - Exiting"
	Quit_or_Run_Again
fi
TRY=1
until /usr/bin/dscl /Search -authonly "$currentUser" "$UserPassword" &>/dev/null; do
    (( TRY++ ))
    DisplayDialogMessage="The password was incorrect. Please try again:"
    /bin/echo "Prompting $currentUser for their Mac password (attempt $TRY)..."
	if [[ -e ${icon} ]] ; then
		UserPassword=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" default answer \"\" with hidden answer with title \"${title}\" with icon POSIX file \"${icon}\"" -e "return text returned of result")
	else
		UserPassword=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" default answer \"\" with hidden answer with title \"${title}\"" -e "return text returned of result")
	fi
	if [ $? -eq 1 ]; then
		/bin/echo "User canceled ${button1} - Exiting"
		Quit_or_Run_Again
	elif (( TRY >= 3 )); then
	    DisplayDialogMessage="You've made three incorrect password attempts. Exiting now."
		button1="Quit"
		if [[ -e ${icon} ]] ; then
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\"} default button 1"
		else
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
		fi
		Quit_or_Run_Again 
    fi
done

if [[ -z "${UserPassword}" ]] ; then
	/bin/echo UserPassword not defined
	/bin/echo Exiting now
	Quit_or_Run_Again
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
}
###
#

#
### Show ReadMe ###
function Show_ReadMe () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
# /bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="${ReadMe}"
/bin/echo "${DisplayDialogMessage}"
title="macOS Security Compliance Project"
button1="Quit"
button2="Proceed"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"} default button 2")
# Stop everything if the Quit button is pressed.
# /bin/echo "${DisplayDialogButtonReturned}"
if [[ "${DisplayDialogButtonReturned}" == *"${button2}"* ]]; then
	/bin/echo "User clicked ${button2}"
else
	/bin/echo "User clicked ${button1}"
	Quit_Project
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Check for softwareupdate ###
function Check_for_softwareupdates () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Checking for Apple Software Updates.

Please be patient this may take some time.

This message will close when complete."
/bin/echo "${DisplayDialogMessage}"
title="Apple Software Updates"
button1="Ok"
icon="/System/Library/PrivateFrameworks/OAHSoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdate.icns"
if [[ -e ${icon} ]] ; then
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\"} default button 1" &
else
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1" &
fi

# Check for softwareupdates requiring a restart
if [[ $(/usr/sbin/softwareupdate -l 2> /dev/null | /usr/bin/grep -c "Action: restart") > 0 ]] ; then
	restartDescription="This system will require a RESTART after updates are installed."
else
	restartDescription="No restart is required."
fi
/usr/bin/killall -q osascript

# Recommended Updates available
RecommendedUpdates="$(/usr/bin/defaults read /Library/Preferences/com.apple.SoftwareUpdate.plist RecommendedUpdates 2> /dev/null | grep "Display Name" | /usr/bin/awk -F '=' '{print $NF}' | tr -d '";' | /usr/bin/sed -e 's/^/-/')"
if [[ "${RecommendedUpdates}" ]] ; then
	/bin/echo "Apple software updates are available."
	openSoftwareUpdatePrefPane
fi
DisplayDialogMessage=""
}
###
#

#
### open Software Update Pref Pane ###
function openSoftwareUpdatePrefPane () {
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="Apple Software Update Available"
DisplayDialogMessage="Use Software Update to install available Apple updates:
${RecommendedUpdates}

${restartDescription}

It is recommended you install all updates before proceeding with the mSPC."
/bin/echo "${DisplayDialogMessage}"
button1="Quit mSCP and Install Apple Updates"
button2="Proceed with mSCP"
icon="/System/Library/PrivateFrameworks/OAHSoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdate.icns"
if [[ -e ${icon} ]] ; then
	DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\",\"${button2}\"} default button 1")
else
	DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"} default button 1")
fi
if [[ "${DisplayDialogButtonReturned}" == *"${button1}"* ]]; then
	/bin/echo "User clicked ${button1}"
	/usr/bin/open x-apple.systempreferences:com.apple.Software-Update-Settings.extension
	/bin/sleep 5
 	Quit_Project
elif [[ "${DisplayDialogButtonReturned}" == *"${button2}"* ]]; then
	/bin/echo "User clicked ${button2}"
	/usr/bin/defaults write ${CFBundleIdentifier} SoftwareUpdate_Deferred_Date -string $(/bin/date "+%Y-%m-%d")
fi
}
###
#

#
### New or Existing Project ###
function New_or_Existing_Project () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Do you want to create a new Project directory - New
or
Do you want to use an existing Project directory - Existing"
/bin/echo "${DisplayDialogMessage}"
title="New or Existing Project"
button1="New"
button2="Existing"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/bin/echo "${DisplayDialogButtonReturned} project"
new_or_existing=${DisplayDialogButtonReturned}
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Are command line tools installed ###
function Are_command_line_tools_installed () {
/usr/bin/xcode-select -p 2> /dev/null
}
###
#

#
### Install Xcode command line tools via command line ###
function Install_Xcode_command_line_tools_via_command_line () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
if ! Are_command_line_tools_installed ; then
	# /usr/bin/clear
	/bin/echo "Checking for Xcode command line tools"
	# Create the placeholder file which is checked by the softwareupdate tool 
	# before allowing the installation of the Xcode command line tools.
	cmd_line_tools_temp_file="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
	/usr/bin/touch "$cmd_line_tools_temp_file"
	cmd_line_tools=$(/usr/sbin/softwareupdate -l | /usr/bin/awk '/\*\ Label: Command Line Tools/ { $1=$1;print }' | /usr/bin/sed 's/^[[ \t]]*//;s/[[ \t]]*$//;s/*//' | /usr/bin/cut -c 9- | /usr/bin/grep -v beta)
	# Check to see if the softwareupdate tool has returned more than one Xcode
	# command line tool installation option. If it has, use the last one listed
	# as that should be the latest Xcode command line tool installer.
	if (( $(/usr/bin/grep -c . <<<"$cmd_line_tools") > 1 )); then
		cmd_line_tools_output="$cmd_line_tools"
		cmd_line_tools=$(/usr/bin/printf "$cmd_line_tools_output" | /usr/bin/tail -1)
		DisplayDialogMessage="Installing ${cmd_line_tools}. 

Please be patient this may take some time.

This message will close when complete."
		/bin/echo "${DisplayDialogMessage}"
		title="Xcode command line tools"
		button1="Ok"
		icon="/System/Library/CoreServices/Install Command Line Developer Tools.app/Contents/Resources/SoftwareUpdate.icns"
		if [[ -e ${icon} ]] ; then
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\"} default button 1" &
		else
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1" &
		fi
		#Install the command line tools
		/usr/sbin/softwareupdate -i "$cmd_line_tools" --verbose
		/usr/bin/killall osascript
		# Remove the temp file
		if [[ -f "$cmd_line_tools_temp_file" ]]; then
			/bin/rm "$cmd_line_tools_temp_file"
		fi
		if ! Are_command_line_tools_installed ; then
			Open_app
			/usr/bin/clear
			/usr/bin/printf "REFRESH\n"
			/bin/echo "Installation of Xcode command line tools failed from the command line. Switching to the slower GUI intallation method."
			DisplayDialogMessage=""
			Install_Xcode_command_line_tools_via_GUI
		fi
	else
		Open_app
		/usr/bin/clear
		/usr/bin/printf "REFRESH\n"
		/bin/echo "Installation of Xcode command line tools failed from the command line. Switching to the slower GUI intallation method."
		# Remove the temp file
		if [[ -f "$cmd_line_tools_temp_file" ]]; then
			/bin/rm "$cmd_line_tools_temp_file"
		fi
		Install_Xcode_command_line_tools_via_GUI
	fi
fi
/usr/bin/xcode-select -v 2> /dev/null
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Install Xcode command line tools via GUI ###
function Install_Xcode_command_line_tools_via_GUI () {
Open_app
# /usr/bin/clear
# /usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
if ! Are_command_line_tools_installed ; then
	# /usr/bin/clear
	/bin/echo ""
	DisplayDialogMessage="Xcode command line tools are required for mSCP."
	/bin/echo "${DisplayDialogMessage}"
	title="Xcode command line tools"
	button1="Install"
	button2="Quit"
	icon="/System/Library/CoreServices/Install Command Line Developer Tools.app/Contents/Resources/SoftwareUpdate.icns"
	if [[ -e ${icon} ]] ; then
		DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\",\"${button2}\"} default button 1")
	else
		DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"} default button 1")
	fi
	/bin/echo "${DisplayDialogButtonReturned}"
	if [[ "${DisplayDialogButtonReturned}" == *"${button2}"* ]]; then
		/bin/echo "User clicked ${button2}"
		Quit_Project
	elif [[ "${DisplayDialogButtonReturned}" == *"${button1}"* ]]; then
		/bin/echo "User clicked ${button1}"
	fi

	/usr/bin/xcode-select --install
	installStatus=$(/usr/bin/pgrep -x "Install Command Line Developer Tools")
	/bin/echo "Installing Command Line Developer Tools"
	while [ "${installStatus}" ]; do
		/bin/sleep 10
		installStatus=$(/usr/bin/pgrep -x "Install Command Line Developer Tools")
	done

	if ! Are_command_line_tools_installed ; then
		/usr/bin/clear
		/usr/bin/printf "REFRESH\n"
		DisplayDialogMessage="Installation of Xcode command line tools failed.
You may have to try from a different network.

You may also try running the command:
xcode-select --install

You may also need to install the full Xcode app."
		/bin/echo "${DisplayDialogMessage}"
		title="Xcode command line tools failure"
		button1="Ok"
		icon="/System/Library/CoreServices/Install Command Line Developer Tools.app/Contents/Resources/SoftwareUpdate.icns"
		if [[ -e ${icon} ]] ; then
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" with icon POSIX file \"${icon}\" buttons {\"${button1}\"} default button 1"
		else
			/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
		fi
		/bin/echo "Command Line Tools were not installed. Exiting now."
		Quit_Project
	fi
	DisplayDialogMessage=""
	Check_for_softwareupdates
	/bin/echo ""
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Validate Python ###
function Validate_Python () {
/bin/echo "${FUNCNAME[0]}"
python3_Path="$(which python3)"
python3_Version=$("${python3_Path}" --version 2> /dev/null)
if [[ -z ${python3_Version} ]] ; then
	/usr/bin/clear
	/usr/bin/printf "REFRESH\n"
	DisplayDialogMessage="Python is required to use ${app_Name}.
		
Python is either not installed, not installed correctly, or an unsupported version of Python is installed.

You may have to run the utility on a fresh Mac system."
	Open_app
	/bin/echo "${DisplayDialogMessage}"
	title="Python Error"
	button1="Quit"
	DisplayDialogButtonReturned=$(/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"}")
	Quit_Project
fi
/bin/echo "${python3_Path} ${python3_Version}"
# /bin/echo "End ${FUNCNAME[0]}"
}
###
#

#
### Check mSCP git availability ###
function Check_mSCP_git_availability () {
Open_app
/bin/echo ""
/bin/echo "${FUNCNAME[0]}"
# Check if the git is available.
Git_Available=$(/usr/bin/curl -Is ${mSCP_github_URL} | head -n 1)
if [[ ! ${Git_Available} ]] ; then
	/usr/bin/clear
	/usr/bin/printf "REFRESH\n"
	DisplayDialogMessage="${mSCP_github_URL} is unavailable. Exiting now."
	/bin/echo "${DisplayDialogMessage}"
	title="mSCP Unavailable"
	button1="Quit"
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
	Quit_or_Run_Again
fi
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Define Branch ###
function Define_Branch () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
if [[ "${sw_build}" == "19" ]] ; then
	defaultBranch="catalina"
	/bin/echo "macOS ${sw_vers_Full} detected."
elif [[ "${sw_build}" == "20" ]] ; then
	defaultBranch="big_sur"
	/bin/echo "macOS ${sw_vers_Full} detected."
elif [[ "${sw_build}" == "21" ]] ; then
	defaultBranch="monterey"
	/bin/echo "macOS ${sw_vers_Full} detected."
elif [[ "${sw_build}" == "22" ]] ; then
	defaultBranch="ventura"
	/bin/echo "macOS ${sw_vers_Full} detected."
elif [[ "${sw_build}" == "23" ]] ; then
	defaultBranch="future_version"
	/bin/echo "macOS ${sw_vers_Full} detected."
fi
/bin/echo "defaultBranch $defaultBranch"

Branches=$(/usr/bin/git ls-remote --heads ${mSCP_github_URL} | /usr/bin/awk -F "/" '{print $NF}')
# Prune the main branch
PrunedBranches=$(/usr/bin/grep -v -w "main" <<< "$Branches")
prod_Branches=$(/usr/bin/printf "${PrunedBranches}" | /usr/bin/grep -v "dev_")
dev_Branches=$(/usr/bin/printf "${PrunedBranches}" | /usr/bin/grep "dev_")

items="${prod_Branches}\n${dev_Branches}\n"
DisplayDialogMessage="You are currently running macOS ${sw_vers_Full} ${macOSName}.

Please select a macOS Security Compliance Project branch from the list:"
title="Choose Branch"
#itemsToList=$(/usr/bin/printf "${items}" | /usr/bin/sort -u | /usr/bin/sed 's/^/\"/' | /usr/bin/sed 's/$/\"/' | /usr/bin/tr "\n" "," | /usr/bin/sed 's/.$//')
itemsToList=$(/usr/bin/printf "${items}" | /usr/bin/sed 's/^/\"/' | /usr/bin/sed 's/$/\"/' | /usr/bin/tr "\n" "," | /usr/bin/sed 's/.$//')
/bin/echo "${DisplayDialogMessage}"
# /bin/echo "${itemsToList}"
## Prompt for a Branch selection
chosenItem=$(/usr/bin/osascript -e 'choose from list {'"$itemsToList"'} with prompt "'"$DisplayDialogMessage"'" with title "'"$title"'" default items "'"$defaultBranch"'"')
macos_security_branch="${chosenItem}"
/bin/echo "Branch chosen ${macos_security_branch}"
if [[ "${chosenItem}" == "false" ]] ; then
	/bin/echo mSCP branch not defined
	/bin/echo Exiting now
	Quit_or_Run_Again
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Define New Directory ###
function Define_New_Directory () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="mSCP Directory"
DisplayDialogMessage="Please choose a parent directory in which to create a NEW macOS Security Compliance Project

For instance: ${currentUserNFSHomeDirectory}/Documents/mSCP_Projects"
/bin/echo "${DisplayDialogMessage}"
button1="Choose Directory"
#/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
ParentDirectory=$(/usr/bin/osascript -e "set theOutputFolder to POSIX path of (choose folder with prompt \"${DisplayDialogMessage}\")")
if [[ -z "${ParentDirectory}" ]] ; then
	/bin/echo ParentDirectory not defined
	/bin/echo Exiting now
	Quit_or_Run_Again
fi
/bin/echo "ParentDirectory: ${ParentDirectory}"
ProjectDirectory="${ParentDirectory}macos_security_${macos_security_branch}_${timeStamp}/"
/bin/echo "ProjectDirectory: ${ProjectDirectory}"
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Validate New Directory ###
function Validate_New_Directory () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
while [ -e "${ParentDirectory}scripts/generate_baseline.py" ]; do
	/bin/echo mSPC parent dirctory not defined. Trying again.
	Define_New_Directory
done
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Define Existing Directory ###
function Define_Existing_Directory () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="mSCP Directory"
DisplayDialogMessage="Please choose an EXISTING macOS Security Compliance Project inside your parent projects directory.

For instance: ${currentUserNFSHomeDirectory}/Documents/mSCP_Projects/existing mSCP directory"
button1="Choose Directory"
#/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
ParentDirectory=$(/usr/bin/osascript -e "set theOutputFolder to POSIX path of (choose folder with prompt \"${DisplayDialogMessage}\")")
if [[ -z "${ParentDirectory}" ]] ; then
	/bin/echo ParentDirectory not defined
	/bin/echo Exiting now
	Quit_or_Run_Again
fi
/bin/echo "ParentDirectory: ${ParentDirectory}"
ProjectDirectory="${ParentDirectory}"
/bin/echo "ProjectDirectory: ${ProjectDirectory}"
/bin/chmod -R +x "${ProjectDirectory}scripts"
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Validate Existing Directory ###
function Validate_Existing_Directory () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
while [ ! -e "${ProjectDirectory}scripts/generate_baseline.py" ]; do
	/bin/echo Existing mSPC dirctory not defined. Trying again.
	Define_Existing_Directory
done
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Download macos_security ###
function Download_macos_security_git () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
# Set working directory to git project directory
pushd "${ProjectDirectory}" 2> /dev/null
# Download 
/usr/bin/git clone ${mSCP_github_URL} --branch "${macos_security_branch}" "${ProjectDirectory}"
/bin/chmod -R +x "${ProjectDirectory}scripts"
# Save discalimer to project directory
/bin/echo "${Disclaimer}" > "${ProjectDirectory}"Apple_Disclaimer.txt
/bin/echo "
Agreed to by:
${currentUserFullName}
${timeStamp}
" >> "${ProjectDirectory}"Apple_Disclaimer.txt
# Set working directory to git project directory
pushd "${ProjectDirectory}" 2> /dev/null
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Download and install macos_security pip3 ###
function Download_and_install_macos_security_pip3 () {
Open_app
# /usr/bin/clear
# /usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
# Set working directory to git project directory
pushd "${ProjectDirectory}" 2> /dev/null
/usr/bin/pip3 install --upgrade pip --user
/usr/bin/pip3 install -r "${ProjectDirectory}requirements.txt" --user
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Proceed to Baselines ###
function Proceed_to_Baselines () {
Open_app
# /usr/bin/clear
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Do you want to generate guidance from a baseline now?"
/bin/echo "${DisplayDialogMessage}"
title="Generate Baseline"
button1="Yes"
button2="No"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "User clicked ${DisplayDialogButtonReturned}"
if [[ "${DisplayDialogButtonReturned}" == "${button1}" ]] ; then
	# Yes
	Select_Baseline
elif [[ "${DisplayDialogButtonReturned}" == "${button2}" ]] ; then
	# No
	No_Guidance
fi
# /bin/echo "End ${FUNCNAME[0]}"
DisplayDialogMessage=""
/bin/echo ""
}
###
#

#
### Select Baseline ###
function Select_Baseline () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
/bin/chmod -R +x "${ProjectDirectory}scripts"
# /bin/echo "generate_baseline command - ${python3_Path} ${ProjectDirectory}scripts/generate_baseline.py"
# Baselines=$("${python3_Path}" "${ProjectDirectory}scripts/generate_baseline.py" -l)
/bin/echo "List available baselines in ${ProjectDirectory}baselines directory"
Baselines=$(/bin/ls "${ProjectDirectory}baselines" | /usr/bin/cut -f 1 -d '.')
if [[ ! ${Baselines} ]] ; then
	DisplayDialogMessage="Something went wrong listing baselines. Exiting now.
See: https://github.com/usnistgov/macos_security/wiki/Generate-a-Baseline

Be sure you have selected an EXISTING macOS Security Compliance Project inside your parent projects directory.

Updates for Xcode Command Line Tools may be required.

You may also be running an alternative version of Python."
	Open_app
	/bin/echo "${DisplayDialogMessage}"
	title="Baseline List"
	button1="Quit"
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
	/usr/bin/open /System/Library/PreferencePanes/SoftwareUpdate.prefPane
	Quit_or_Run_Again
fi
items="${Baselines}"
DisplayDialogMessage="Please select a baseline from the list:"
title="Select Baseline"
itemsToList=$(/usr/bin/printf "${items}" | /usr/bin/sort -u | sed '1s/^/Use_Custom_Baseline\n/' | /usr/bin/sed 's/^/\"/' | /usr/bin/sed 's/$/\"/' | /usr/bin/tr "\n" "," | /usr/bin/sed 's/.$//')
## Prompt for a Branch selection
/bin/echo "${DisplayDialogMessage}"
# /bin/echo "${itemsToList}"
chosenItem=$(/usr/bin/osascript -e 'choose from list {'"$itemsToList"'} with prompt "'"$DisplayDialogMessage"'" with title "'"$title"'"')
if [[ "${chosenItem}" == "false" ]] ; then
	echo "User clicked cancel - Exiting"
	Quit_or_Run_Again
fi
Selected_Baseline="${chosenItem}"
echo "Baseline chosen ${Selected_Baseline}"

if [[ "${Selected_Baseline}" == "Use_Custom_Baseline" ]] ; then
	Selected_Baseline=""
	DisplayDialogMessage=""
	Select_Custom_Baseline
else
	Standard_or_Custom_Baseline
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Select Custom Baseline ###
function Select_Custom_Baseline () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
Custom_Baseline_Path=""
title="Custom Baseline yaml file"
DisplayDialogMessage="Please choose an existing Custom Baseline yaml file to use with the project"
/bin/echo "${DisplayDialogMessage}"
button1="Choose"
#/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
Custom_Baseline_Path=$(/usr/bin/osascript -e "set theDocument to POSIX path of (choose file with prompt \"${DisplayDialogMessage}\")")
if [[ -z "${Custom_Baseline_Path}" ]] ; then
	/bin/echo Custom_Baseline_Path not defined
	/bin/echo Exiting now
	Quit_or_Run_Again
fi
/bin/echo "Custom_Baseline_Path: ${Custom_Baseline_Path}"
# 
Selected_Baseline_file=$(/usr/bin/basename "${Custom_Baseline_Path}")
Selected_Baseline="${Selected_Baseline_file%.*}"
/bin/echo "Selected_Baseline is ${Selected_Baseline}"
#
/bin/mkdir -p "${ProjectDirectory}build/baselines/"
/bin/cp "${Custom_Baseline_Path}" "${ProjectDirectory}build/baselines/"
DisplayDialogMessage=""
Generate_Guidance
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Standard or Custom Baseline ###
function Standard_or_Custom_Baseline () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Do you want to use a standard baseline or a custom baseline?"
/bin/echo "${DisplayDialogMessage}"
title="Standard or Custom"
button1="Standard"
button2="Custom"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${DisplayDialogButtonReturned} baseline"
if [[ "${DisplayDialogButtonReturned}" == "${button1}" ]] ; then
	# Standard
	DisplayDialogMessage=""
	Define_Baseline
elif [[ "${DisplayDialogButtonReturned}" == "${button2}" ]] ; then
	# Custom
	DisplayDialogMessage=""
	Define_Baseline_Custom
fi
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Define Baseline ###
function Define_Baseline () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
# /bin/echo "generate_baseline command - ${python3_Path} ${ProjectDirectory}scripts/generate_baseline.py"
# "${python3_Path}" "${ProjectDirectory}scripts/generate_baseline.py" -k "${Selected_Baseline}"
/bin/echo "copy ${Selected_Baseline} to ${ProjectDirectory}build/baselines"
/bin/mkdir -p "${ProjectDirectory}build/baselines/"
/bin/cp "${ProjectDirectory}/baselines/${Selected_Baseline}.yaml" "${ProjectDirectory}build/baselines/"
Generate_Guidance
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Define Baseline Custom ###
function Define_Baseline_Custom () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"

# Organization Name
title="Organization Name"
DisplayDialogMessage="Please enter your organization's name:"
button1="Ok"
OrgName=$(/usr/bin/osascript -e "text returned of (display dialog \"${DisplayDialogMessage}\" default answer \"YourOrg\" with title \"${title}\" buttons {\"${button1}\"})" | /usr/bin/sed 's/ /_/g')

# customize baseline name
title="Custom Baseline Name"
DisplayDialogMessage="Please create a custom baseline name.

Example: ${Selected_Baseline}-${OrgName}"
button1="Ok"
CustomBaselineName=$(/usr/bin/osascript -e "text returned of (display dialog \"${DisplayDialogMessage}\" default answer \"${Selected_Baseline}-${OrgName}\" with title \"${title}\" buttons {\"${button1}\"})" | /usr/bin/sed 's/ /_/g')
/bin/echo "Custom baseline name: ${CustomBaselineName}
		
Please be patient this may take some time.
"

# backup exiting ${Selected_Baseline}.yaml
/bin/mv "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml" "${ProjectDirectory}build/baselines/${Selected_Baseline}-tmp.yaml" &>/dev/null
# generate standard baseline
# /bin/echo "generate_baseline command - ${python3_Path} ${ProjectDirectory}scripts/generate_baseline.py"
# "${python3_Path}" "${ProjectDirectory}scripts/generate_baseline.py" -k "${Selected_Baseline}"
/bin/echo "copy ${Selected_Baseline} to ${ProjectDirectory}build/baselines"
/bin/mkdir -p "${ProjectDirectory}build/baselines/"
/bin/cp "${ProjectDirectory}/baselines/${Selected_Baseline}.yaml" "${ProjectDirectory}build/baselines/"

# rename baseline to ${CustomBaselineName}.yaml
/bin/mv "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml" "${ProjectDirectory}build/baselines/${CustomBaselineName}.yaml"
# restore exiting ${Selected_Baseline}.yaml
/bin/mv "${ProjectDirectory}build/baselines/${Selected_Baseline}-tmp.yaml" "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml" &>/dev/null

# Generate Guidance pdf as reference
/bin/cp "${ProjectDirectory}build/baselines/${CustomBaselineName}.yaml" "${ProjectDirectory}build/baselines/${Selected_Baseline}-reference.yaml"
/bin/echo "generate_guidance command - ${python3_Path} ${ProjectDirectory}scripts/generate_guidance.py"
"${python3_Path}" "${ProjectDirectory}scripts/generate_guidance.py" -p -x "${ProjectDirectory}build/baselines/${Selected_Baseline}-reference.yaml"
### Check for generate_guidance.py errors
if [[ "$?" == "1" ]] ; then
	Bad_YAML
fi
/bin/mv "${ProjectDirectory}build/${Selected_Baseline}-reference/${Selected_Baseline}-reference.pdf" "${ProjectDirectory}build/baselines/${Selected_Baseline}-reference.pdf"
/bin/mv "${ProjectDirectory}build/${Selected_Baseline}-reference/${Selected_Baseline}-reference.xls" "${ProjectDirectory}build/baselines/${Selected_Baseline}-reference.xls"
/bin/rm -R "${ProjectDirectory}build/${Selected_Baseline}-reference/" "${ProjectDirectory}build/baselines/${Selected_Baseline}-reference.yaml"

# Add "${OrgName}" to the end of "title: " in "${ProjectDirectory}build/baselines/${CustomBaselineName}.yaml"
/usr/bin/sed -i.bak "/title: /s/\"$/ - ${OrgName}&/" "${ProjectDirectory}build/baselines/${CustomBaselineName}.yaml"
/bin/rm "${ProjectDirectory}build/baselines/${CustomBaselineName}.yaml.bak"

Selected_Baseline="${CustomBaselineName}"
Open_app
/usr/bin/open "${ProjectDirectory}build/baselines/"
/bin/sleep 3
title="Custom Baseline"
DisplayDialogMessage="DO NOT CLICK PROCEED YET!

The ${CustomBaselineName}.yaml baseline and ${Selected_Baseline}-reference.pdf have been saved to: 
${ProjectDirectory}build/baselines/

The baseline directory will now open in the Finder.

--

The ${Selected_Baseline}-reference.pdf may be used to review the standard ${Selected_Baseline} baseline rules.

Open ${CustomBaselineName}.yaml in a text editor if you wish to customize it.
Comment out (using #) rules and/or sections that are not applicable to your environment.
If appropriate add your name and organization to the authors section.
Save ${CustomBaselineName}.yaml

For baseline details see: https://github.com/usnistgov/macos_security/wiki/Baselines

--

Additionally you may choose to customize project rules for your environment.
For cusomization details see: https://github.com/usnistgov/macos_security/wiki/Customization

--

Once customization is complete click Proceed."
button1="Proceed"
/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"}"
DisplayDialogMessage=""
Generate_Guidance
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Generate Guidance ###
function Generate_Guidance () {
Open_app
/usr/bin/clear
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Do you want to customize the ${Selected_Baseline} guidance report with a logo?

Square or horizontal format at least 1000px x 1000px is recommended."
/bin/echo "${DisplayDialogMessage}"
title="Logo"
button1="Yes"
button2="No"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "User clicked ${DisplayDialogButtonReturned}"
if [[ "${DisplayDialogButtonReturned}" == "${button1}" ]] ; then
	Open_app
	/bin/echo "Select a logo"
	title="Logo File"
	DisplayDialogMessage="Please select a logo file to use with the project. Square or horizontal format at least 1000px x 1000px is recommended."
	button1="Proceed"
	LOGO_Path=$(/usr/bin/osascript -e "set theDocument to POSIX path of (choose file with prompt \"${DisplayDialogMessage}\")")
	if [[ -z "${LOGO_Path}" ]] ; then
		/bin/echo "A logo was not selected"
		Open_app
		/bin/echo "Generating guidance without a logo
		
Please be patient this may take some time.
"
		/bin/echo "generate_guidance command - ${python3_Path} ${ProjectDirectory}scripts/generate_guidance.py"
		"${python3_Path}" "${ProjectDirectory}scripts/generate_guidance.py" -s -p -x "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml"
	else
		#Establish target pixelHeight and target pixelWidth
		target_pixelHeight="1000"
		target_pixelWidth="2000"
		
		/bin/echo "LOGO_Path is ${LOGO_Path}"
		LOGO_Dir=$(/usr/bin/dirname "${LOGO_Path}")
		#/bin/echo "LOGO_Dir is ${LOGO_Dir}"
		LOGO_File=$(/usr/bin/basename "${LOGO_Path}")
		#/bin/echo "LOGO_File is ${LOGO_File}"
		LOGO_filename="${LOGO_File%.*}"
		#/bin/echo "LOGO_filename is ${LOGO_filename}"
		LOGO_extension="${LOGO_File##*.}"
		#/bin/echo "LOGO_extension is ${LOGO_extension}"
		LOGO_new="${ProjectDirectory}build/${LOGO_filename}-${target_pixelHeight}x${target_pixelWidth}.${LOGO_extension}"
		/bin/echo "LOGO_new is ${LOGO_new}"
		/bin/cp "${LOGO_Path}" "${LOGO_new}"

		# Determine current pixelWidth and pixelHeight
		LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
		LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
		/bin/echo "Starting LOGO_new_pixelHeight: ${LOGO_new_pixelHeight}"
		/bin/echo "Starting LOGO_new_pixelWidth: ${LOGO_new_pixelWidth}"

		# Adjust pixel width and height for horizontal logo file
		if [[ ${LOGO_new_pixelHeight} -lt ${LOGO_new_pixelWidth} ]]; then
			/bin/echo "Working with a horizontal logo"
			/usr/bin/sips --resampleHeight ${target_pixelHeight} "${LOGO_new}"
			LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
			LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
			if [[ ${LOGO_new_pixelWidth} -gt ${target_pixelWidth} ]]; then
				/bin/echo "resampleWidth ${target_pixelWidth}"
				/usr/bin/sips --resampleWidth ${target_pixelWidth} "${LOGO_new}"
			fi
			LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
			LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
			if [[ ${LOGO_new_pixelHeight} -gt ${target_pixelHeight} ]]; then
				/bin/echo "resampleHeight ${target_pixelHeight}"
				/usr/bin/sips --resampleHeight ${target_pixelHeight} "${LOGO_new}"
			fi
			/bin/echo "cropToHeightWidth ${target_pixelHeight} ${target_pixelWidth}"
			/usr/bin/sips --cropToHeightWidth ${target_pixelHeight} ${target_pixelWidth} "${LOGO_new}"
			#
			LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
			LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
		fi
		
		# Adjust pixel width and height for square or verticle logo file
		if [[ ${LOGO_new_pixelHeight} -gt ${LOGO_new_pixelWidth} ]] || [[ ${LOGO_new_pixelHeight} -eq ${LOGO_new_pixelWidth} ]]; then
			/bin/echo "Workinging with a square or verticle logo"
			/usr/bin/sips --resampleWidth ${target_pixelWidth} "${LOGO_new}"
			LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
			LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
			if [[ ${LOGO_new_pixelHeight} -gt ${target_pixelHeight} ]]; then
				/bin/echo "resampleHeight ${target_pixelHeight}"
				/usr/bin/sips --resampleHeight ${target_pixelHeight} "${LOGO_new}"
			fi
			/bin/echo "cropToHeightWidth ${target_pixelHeight} ${target_pixelWidth}"
			/usr/bin/sips --cropToHeightWidth ${target_pixelHeight} ${target_pixelWidth} "${LOGO_new}"
			#
			LOGO_new_pixelHeight=$(/usr/bin/sips --getProperty pixelHeight "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelHeight:/{print $2}')
			LOGO_new_pixelWidth=$(/usr/bin/sips --getProperty pixelWidth "${LOGO_new}" 2> /dev/null | /usr/bin/awk '/pixelWidth:/{print $2}')
		fi

		/bin/echo "Final LOGO_new_pixelHeight: ${LOGO_new_pixelHeight}"
		/bin/echo "Final LOGO_new_pixelWidth: ${LOGO_new_pixelWidth}"

		Open_app
		/bin/echo "Generating guidance with a logo.
		
Please be patient this may take some time.
"
		/bin/echo "generate_guidance command - ${python3_Path} ${ProjectDirectory}scripts/generate_guidance.py"
		"${python3_Path}" "${ProjectDirectory}scripts/generate_guidance.py" -s -p -x -l "${LOGO_new}" "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml"
	fi
elif [[ "${DisplayDialogButtonReturned}" == "${button2}" ]] ; then
	Open_app
	/bin/echo "Generating guidance without a logo
		
Please be patient this may take some time.
"
	/bin/echo "generate_guidance command - ${python3_Path} ${ProjectDirectory}scripts/generate_guidance.py"
	"${python3_Path}" "${ProjectDirectory}scripts/generate_guidance.py" -s -p -x "${ProjectDirectory}build/baselines/${Selected_Baseline}.yaml"
fi

### Check for generate_guidance.py errors
if [[ "$?" == "1" ]] ; then
	Bad_YAML
fi
DisplayDialogMessage=""

Create_Extension_Attributes

Create_ReadMe_rtf_within_baseline_directory

Open_baseline_directory

# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Bad YAML ###
function Bad_YAML () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="Bad YAML"
DisplayDialogMessage="Error generating guidance!

The ${Selected_Baseline}.yaml appears to be improperly formatted."
button1="Quit"
/bin/echo "${DisplayDialogMessage}"
/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
/bin/sleep 1
Quit_or_Run_Again
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### No Guidance ###
function No_Guidance () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="mSCP"
DisplayDialogMessage="The macOS Security Compliance Project has been saved to: 
${ProjectDirectory}

The project directory will now open in the Finder."
button1="Ok"
/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
/usr/bin/open "${ProjectDirectory}"
/bin/sleep 3
Quit_or_Run_Again
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Open baseline directory ###
function Open_baseline_directory () {
Open_app
# /usr/bin/clear
# /usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
title="mSCP"
DisplayDialogMessage="Do you want to check (audit) the current compliance of this system now?"
/bin/echo "${DisplayDialogMessage}"
title="Check compliance?"
button1="Yes"
button2="No"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/bin/echo "User clicked ${DisplayDialogButtonReturned}"
if [[ "${DisplayDialogButtonReturned}" == "${button1}" ]] ; then
	Get_UserPassword
	if [[ -z "${UserPassword}" ]] ; then
		/bin/echo UserPassword not defined
		DisplayDialogMessage=""
		Get_UserPassword
	fi
	/bin/echo ""
	/bin/echo "Compliance Results"
	/bin/echo ${UserPassword} | /usr/bin/sudo -S "${ProjectDirectory}build/${Selected_Baseline}/${Selected_Baseline}_compliance.sh" --check
	STATS=$(/bin/echo ${UserPassword} | /usr/bin/sudo -S "${ProjectDirectory}build/${Selected_Baseline}/${Selected_Baseline}_compliance.sh" --stats)
	title="Compliance Results"
	DisplayDialogMessage="${Selected_Baseline} compliance results:
${STATS}

Results written to /Library/Logs/${Selected_Baseline}_baseline.log

Your macOS Security Compliance Project ${Selected_Baseline} baseline guidance has been saved to: 
${ProjectDirectory}build/${Selected_Baseline}

It will now open in the Finder.
Please review the ${Selected_Baseline}/_ReadMe_mSCP.rtf"
	button1="Ok"
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
	Open_app
	/bin/echo ""
	/bin/echo "${DisplayDialogMessage}"
	/usr/bin/open "/Library/Logs/${Selected_Baseline}_baseline.log"
	/usr/bin/open "${ProjectDirectory}build/${Selected_Baseline}"
	Quit_or_Run_Again
else
	title="mSCP"
DisplayDialogMessage="Your macOS Security Compliance Project ${Selected_Baseline} baseline guidance has been saved to: 
${ProjectDirectory}build/${Selected_Baseline}

It will now open in the Finder.
Please review the ${Selected_Baseline}/_ReadMe_mSCP.rtf"
	button1="Ok"
	/usr/bin/osascript -e "display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\"} default button 1"
	Open_app
	/bin/echo ""
	/bin/echo "${DisplayDialogMessage}"
	/usr/bin/open "${ProjectDirectory}build/${Selected_Baseline}"
	Quit_or_Run_Again
fi
DisplayDialogMessage=""
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Create Extension Attributes ###
function Create_Extension_Attributes (){
# /usr/bin/clear
# /usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
# Define MDM_Resources directories
MDM_Resources_Directory="${ProjectDirectory}build/${Selected_Baseline}/MDM_Resources"
MDM_Resources_Directory_Jamf_Extension_Attributes="${MDM_Resources_Directory}/Jamf_Extension_Attributes_xml"
MDM_Resources_Directory_MDM_Inventory_shell_scripts="${MDM_Resources_Directory}/MDM_Inventory_shell_scripts"
# make MDM_Resources directories
/bin/mkdir -p "${MDM_Resources_Directory}"
/bin/mkdir -p "${MDM_Resources_Directory_Jamf_Extension_Attributes}"
/bin/mkdir -p "${MDM_Resources_Directory_MDM_Inventory_shell_scripts}"
# Define Jamf Extension Attributes xml
compliance_exemptions_xml="${MDM_Resources_Directory_Jamf_Extension_Attributes}/compliance-exemptions.xml"
compliance_FailedResultsCount_xml="${MDM_Resources_Directory_Jamf_Extension_Attributes}/compliance-FailedResultsCount.xml"
compliance_FailedResultsList_xml="${MDM_Resources_Directory_Jamf_Extension_Attributes}/compliance-FailedResultsList.xml"
compliance_version_xml="${MDM_Resources_Directory_Jamf_Extension_Attributes}/compliance-version.xml"
# Define MDM Inventory shell scripts
compliance_exemptions_sh="${MDM_Resources_Directory_MDM_Inventory_shell_scripts}/compliance-exemptions.sh"
compliance_FailedResultsCount_sh="${MDM_Resources_Directory_MDM_Inventory_shell_scripts}/compliance-FailedResultsCount.sh"
compliance_FailedResultsList_sh="${MDM_Resources_Directory_MDM_Inventory_shell_scripts}/compliance-FailedResultsList.sh"
compliance_version_sh="${MDM_Resources_Directory_MDM_Inventory_shell_scripts}/compliance-version.sh"
#
/bin/echo "Make compliance-exemptions.xml"
/bin/cat > "${compliance_exemptions_xml}" << compliance_exemptions_xml
<?xml version="1.0" encoding="UTF-8"?>
<extensionAttribute>
<displayName>Compliance - Exemptions</displayName>
<displayInCategory>Operating System</displayInCategory>
<dataType>string</dataType>
<description>Displays the exemptions version being used.</description>
<scriptContentsMac>#!/bin/bash
######
# Used to gather the exemptions being used.
######

audit=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
EXEMPT_RULES=()

if [[ ! -z &quot;\$audit&quot; ]]; then

    count=\$(echo &quot;\$audit&quot; | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ &quot;\$count&quot; == 1 ]]; then
        auditfile=&quot;/Library/Managed Preferences/\${audit}&quot;
        if [[ ! -e &quot;\$auditfile&quot; ]];then
                auditfile=&quot;/Library/Preferences/\${audit}&quot;
        fi

        rules=(\$(/usr/libexec/PlistBuddy -c &quot;print :&quot; &quot;\${auditfile}&quot; | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == &quot;Dict&quot; ]]; then
                continue
            fi
            exemptions=\$(/usr/libexec/PlistBuddy -c &quot;print :\$rule:exempt&quot; &quot;\${auditfile}&quot; 2&gt;/dev/null)
            if [[ &quot;\$exemptions&quot; == &quot;true&quot; ]]; then
                EXEMPT_RULES+=(\$rule)
            fi
        done
              

    else
        EXEMPT_RULES=&quot;Multiple Baselines Found&quot;
    fi
else
    EXEMPT_RULES=&quot;No Baseline Set&quot;
fi
    if [[ \${#EXEMPT_RULES[@]} == 0 ]]; then
        EXEMPT_RULES=&quot;No Exemptions Set&quot;
    fi

# sort the results
IFS=\$'
' sorted=(\$(/usr/bin/sort &lt;&lt;&lt;&quot;\${EXEMPT_RULES[*]}&quot;)); unset IFS

printf &quot;&lt;result&gt;&quot;
printf &quot;%s
&quot; &quot;\${sorted[@]}&quot;
printf &quot;&lt;/result&gt;&quot;
</scriptContentsMac>
</extensionAttribute>
compliance_exemptions_xml

/bin/echo "Make compliance-FailedResultsCount.xml"
/bin/cat > "${compliance_FailedResultsCount_xml}" << compliance_FailedResultsCount_xml
<?xml version="1.0" encoding="UTF-8"?>
<extensionAttribute>
<displayName>Compliance - Failed Results Count</displayName>
<displayInCategory>Operating System</displayInCategory>
<dataType>number</dataType>
<description>Displays the number of compliance controls that failed.</description>
<scriptContentsMac>#!/bin/bash
######
# Used to gather the total number of failed results from the compliance audit.
######

audit=\$(ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
EXEMPT_RULES=()
FAILED_RULES=()

if [[ ! -z &quot;\$audit&quot; ]]; then

    count=\$(echo &quot;\$audit&quot; | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ &quot;\$count&quot; == 1 ]]; then
    
        # Get the Exemptions
        exemptfile=&quot;/Library/Managed Preferences/\${audit}&quot;
        if [[ ! -e &quot;\$exemptfile&quot; ]];then
            exemptfile=&quot;/Library/Preferences/\${audit}&quot;
        fi

        rules=(\$(/usr/libexec/PlistBuddy -c &quot;print :&quot; &quot;\${exemptfile}&quot; | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == &quot;Dict&quot; ]]; then
                continue
            fi
            EXEMPTIONS=\$(/usr/libexec/PlistBuddy -c &quot;print :\$rule:exempt&quot; &quot;\${exemptfile}&quot; 2&gt;/dev/null)
            if [[ &quot;\$EXEMPTIONS&quot; == &quot;true&quot; ]]; then
                EXEMPT_RULES+=(\$rule)
            fi
        done
        
        unset \$rules

        # Get the Findings
        auditfile=&quot;/Library/Preferences/\${audit}&quot;
        rules=(\$(/usr/libexec/PlistBuddy -c &quot;print :&quot; &quot;\${auditfile}&quot; | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == &quot;Dict&quot; ]]; then
                continue
            fi
            FINDING=\$(/usr/libexec/PlistBuddy -c &quot;print :\$rule:finding&quot; &quot;\${auditfile}&quot;)
            if [[ &quot;\$FINDING&quot; == &quot;true&quot; ]]; then
                FAILED_RULES+=(\$rule)
            fi
        done
        # count items only in Findings
        count=0
        for finding in \${FAILED_RULES[@]}; do
            if [[ ! &quot; \${EXEMPT_RULES[*]} &quot; =~ &quot; \${finding} &quot; ]] ;then
                ((count=count+1))
            fi
        done
    else
        count=&quot;-2&quot;
    fi
else
    count=&quot;-1&quot;
fi

/bin/echo &quot;&lt;result&gt;\${count}&lt;/result&gt;&quot;
</scriptContentsMac>
</extensionAttribute>
compliance_FailedResultsCount_xml

/bin/echo "Make compliance-FailedResultsList.xml"
/bin/cat > "${compliance_FailedResultsList_xml}" << compliance_FailedResultsList_xml
<?xml version="1.0" encoding="UTF-8"?>
<extensionAttribute>
<displayName>Compliance - Failed Result List</displayName>
<displayInCategory>Operating System</displayInCategory>
<dataType>string</dataType>
<description>Displays the list of compliance controls that failed.</description>
<scriptContentsMac>#!/bin/bash
######
# Used to gather the list of failed controls from the compliance audit.
######

audit=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
FAILED_RULES=()
if [[ ! -z &quot;\$audit&quot; ]]; then

    count=\$(echo &quot;\$audit&quot; | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ &quot;\$count&quot; == 1 ]]; then
        auditfile=&quot;/Library/Preferences/\${audit}&quot;

        rules=(\$(/usr/libexec/PlistBuddy -c &quot;print :&quot; &quot;\${auditfile}&quot; | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == &quot;Dict&quot; ]]; then
                continue
            fi
            FINDING=\$(/usr/libexec/PlistBuddy -c &quot;print :\$rule:finding&quot; &quot;\${auditfile}&quot;)
            if [[ &quot;\$FINDING&quot; == &quot;true&quot; ]]; then
                FAILED_RULES+=(\$rule)
            fi
        done
              
    else
        FAILED_RULES=&quot;Multiple Baselines Found&quot;
    fi
else
    FAILED_RULES=&quot;No Baseline Set&quot;
fi

# sort the results
IFS=\$'
' sorted=(\$(/usr/bin/sort &lt;&lt;&lt;&quot;\${FAILED_RULES[*]}&quot;)); unset IFS

printf &quot;&lt;result&gt;&quot;
printf &quot;%s
&quot; &quot;\${sorted[@]}&quot;
printf &quot;&lt;/result&gt;&quot;
</scriptContentsMac>
</extensionAttribute>
compliance_FailedResultsList_xml

/bin/echo "Make compliance-version.xml"
/bin/cat > "${compliance_version_xml}" << compliance_version_xml
<?xml version="1.0" encoding="UTF-8"?>
<extensionAttribute>
<displayName>Compliance - Version</displayName>
<displayInCategory>Operating System</displayInCategory>
<dataType>string</dataType>
<description>Displays the baseline version being used.</description>
<scriptContentsMac>#!/bin/bash
######
# Used to gather the baseline version being used.
######

result=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep &quot;org.*.audit.plist&quot; | /usr/bin/awk '{print \$NF}')

if [[ ! -z &quot;\$result&quot; ]]; then
    count=\$(echo &quot;\$result&quot; | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ &quot;\$count&quot; != 1 ]]; then
        result=&quot;Multiple Baselines Set&quot;
    fi
else result=&quot;No Baseline Set&quot;
fi
echo &quot;&lt;result&gt;\$result&lt;/result&gt;&quot;
</scriptContentsMac>
</extensionAttribute>
compliance_version_xml

/bin/echo "Make compliance-exemptions.sh"
/bin/cat > "${compliance_exemptions_sh}" << compliance_exemptions_sh
#!/bin/bash
######
# Used to gather the exemptions being used.
######

audit=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
EXEMPT_RULES=()

if [[ ! -z "\$audit" ]]; then

    count=\$(echo "\$audit" | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ "\$count" == 1 ]]; then
        auditfile="/Library/Managed Preferences/\${audit}"
        if [[ ! -e "\$auditfile" ]];then
                auditfile="/Library/Preferences/\${audit}"
        fi

        rules=(\$(/usr/libexec/PlistBuddy -c "print :" "\${auditfile}" | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == "Dict" ]]; then
                continue
            fi
            exemptions=\$(/usr/libexec/PlistBuddy -c "print :\$rule:exempt" "\${auditfile}" 2>/dev/null)
            if [[ "\$exemptions" == "true" ]]; then
                EXEMPT_RULES+=(\$rule)
            fi
        done
              

    else
        EXEMPT_RULES="Multiple Baselines Found"
    fi
else
    EXEMPT_RULES="No Baseline Set"
fi
    if [[ \${#EXEMPT_RULES[@]} == 0 ]]; then
        EXEMPT_RULES="No Exemptions Set"
    fi

# sort the results
IFS=\$'
' sorted=(\$(/usr/bin/sort <<<"\${EXEMPT_RULES[*]}")); unset IFS

printf "<result>"
printf "%s
" "\${sorted[@]}"
printf "</result>"
compliance_exemptions_sh

/bin/echo "Make compliance-FailedResultsCount.sh"
/bin/cat > "${compliance_FailedResultsCount_sh}" << compliance_FailedResultsCount_sh
#!/bin/bash
######
# Used to gather the total number of failed results from the compliance audit.
######

audit=\$(ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
EXEMPT_RULES=()
FAILED_RULES=()

if [[ ! -z "\$audit" ]]; then

    count=\$(echo "\$audit" | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ "\$count" == 1 ]]; then
    
        # Get the Exemptions
        exemptfile="/Library/Managed Preferences/\${audit}"
        if [[ ! -e "\$exemptfile" ]];then
            exemptfile="/Library/Preferences/\${audit}"
        fi

        rules=(\$(/usr/libexec/PlistBuddy -c "print :" "\${exemptfile}" | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == "Dict" ]]; then
                continue
            fi
            EXEMPTIONS=\$(/usr/libexec/PlistBuddy -c "print :\$rule:exempt" "\${exemptfile}" 2>/dev/null)
            if [[ "\$EXEMPTIONS" == "true" ]]; then
                EXEMPT_RULES+=(\$rule)
            fi
        done
        
        unset \$rules

        # Get the Findings
        auditfile="/Library/Preferences/\${audit}"
        rules=(\$(/usr/libexec/PlistBuddy -c "print :" "\${auditfile}" | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == "Dict" ]]; then
                continue
            fi
            FINDING=\$(/usr/libexec/PlistBuddy -c "print :\$rule:finding" "\${auditfile}")
            if [[ "\$FINDING" == "true" ]]; then
                FAILED_RULES+=(\$rule)
            fi
        done
        # count items only in Findings
        count=0
        for finding in \${FAILED_RULES[@]}; do
            if [[ ! " \${EXEMPT_RULES[*]} " =~ " \${finding} " ]] ;then
                ((count=count+1))
            fi
        done
    else
        count="-2"
    fi
else
    count="-1"
fi

/bin/echo "<result>\${count}</result>"
compliance_FailedResultsCount_sh

/bin/echo "Make compliance-FailedResultsList.sh"
/bin/cat > "${compliance_FailedResultsList_sh}" << compliance_FailedResultsList_sh
#!/bin/bash
######
# Used to gather the list of failed controls from the compliance audit.
######

audit=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep 'org.*.audit.plist' | /usr/bin/awk '{print \$NF}')
FAILED_RULES=()
if [[ ! -z "\$audit" ]]; then

    count=\$(echo "\$audit" | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ "\$count" == 1 ]]; then
        auditfile="/Library/Preferences/\${audit}"

        rules=(\$(/usr/libexec/PlistBuddy -c "print :" "\${auditfile}" | /usr/bin/awk '/Dict/ { print \$1 }'))
        
        for rule in \${rules[*]}; do
            if [[ \$rule == "Dict" ]]; then
                continue
            fi
            FINDING=\$(/usr/libexec/PlistBuddy -c "print :\$rule:finding" "\${auditfile}")
            if [[ "\$FINDING" == "true" ]]; then
                FAILED_RULES+=(\$rule)
            fi
        done
              

    else
        FAILED_RULES="Multiple Baselines Found"
    fi
else
    FAILED_RULES="No Baseline Set"
fi

# sort the results
IFS=\$'
' sorted=(\$(/usr/bin/sort <<<"\${FAILED_RULES[*]}")); unset IFS

printf "<result>"
printf "%s
" "\${sorted[@]}"
printf "</result>"
compliance_FailedResultsList_sh

# Make compliance-version.sh
/bin/cat > "${compliance_version_sh}" << compliance_version_sh
#!/bin/bash
######
# Used to gather the baseline version being used.
######

result=\$(/bin/ls -l /Library/Preferences | /usr/bin/grep "org.*.audit.plist" | /usr/bin/awk '{print \$NF}')

if [[ ! -z "\$result" ]]; then
    count=\$(echo "\$result" | /usr/bin/wc -l | /usr/bin/xargs)
    if [[ "\$count" != 1 ]]; then
        result="Multiple Baselines Set"
    fi
else result="No Baseline Set"
fi
echo "<result>\$result</result>"
compliance_version_sh

/bin/chmod +x "${MDM_Resources_Directory_MDM_Inventory_shell_scripts}"/*.sh
#/bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Create ReadMe rtf within baseline directory ###
function Create_ReadMe_rtf_within_baseline_directory (){
/bin/echo "${FUNCNAME[0]}"
/bin/cat > "${ProjectDirectory}build/${Selected_Baseline}/_ReadMe_mSCP.rtf" << ReadMe_mSCP
{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fswiss\fcharset0 Helvetica-Bold;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh14320\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs28 \cf0 \\
\\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\ri-1444\pardirnatural\partightenfactor0
\cf0 \\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\ri-1444\pardirnatural\qc\partightenfactor0

\f1\b \cf0 Welcome to the macOS Security Compliance Project\\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\ri-1444\pardirnatural\partightenfactor0

\f0\b0 \cf0 \\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0
\cf0 The mSCP Setup Utility has generated a series of scripts, profiles, plists, and files to make it easier to implement security and compliance guidance using a mobile device management (MDM) tool.\\
The guidance is ideally implemented via MDM. The generated documentation and guidance can be utilized throughout your organization.\\
\\
IT IS HIGHLY RECOMMENDED TO REVIEW THE PROJECT WIKI BEFORE PROCEEDING.\\
{\field{\*\fldinst{HYPERLINK "https://github.com/usnistgov/macos_security/wiki"}}{\fldrslt https://github.com/usnistgov/macos_security/wiki}}\\
\\
TEST IN A DEVELOPMENT ENVIRONMENT FIRST\\
\\
NOTE: Using the compliance scripts generated by the mSCP to fix (remediate) can make changes (by design) to a Mac system that may seriously restrict capabilities\'a0(such as login)\'a0if certain policies are not met.\\
\\
Best practice is to initially ONLY run the compliance scripts to check (audit) Mac systems. Manually evaluate each rule before implementation using the interactive script or rule descriptions in the baseline documentation guide. It is important to note that these results are provided as guidance. It is IMPERATIVE that your organization review the provided controls and make appropriate risk based decisions to adopt or ignore any recommended policy herein, based on the operational and security needs of the organization.\\
\\
_______________\\
\\
${Selected_Baseline} directory manifest:\\
_ReadMe_mSCP.rtf (this file)\\
${Selected_Baseline}_compliance.sh\\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\tx9357\tx10080\pardirnatural\partightenfactor0
\cf0 ${Selected_Baseline}.adoc\\
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0
\cf0 ${Selected_Baseline}.html\\
${Selected_Baseline}.pdf\\
${Selected_Baseline}.xls\\
MDM_Resources (directory) \\
	Jamf_Extension_Attributes_xml (directory)\\
		compliance-exemptions.xml\\
		compliance-FailedResultsCount.xml\\
		compliance-FailedResultsList.xml\\
		compliance-version.xml\\
	MDM_Inventory_shell_scripts (directory)\\
		compliance-exemptions.sh\\
		compliance-FailedResultsCount.sh\\
		compliance-FailedResultsList.sh\\
		compliance-version.sh\\
mobileconfigs (directory) \\
	-preferences (directory)\\
	-unsigned (or signed, if script was run with a signing cert) (directory)\\
Preferences (directory)\\
	-${Selected_Baseline}.audit.plist\\
\\
_______________\\
\\
Description of contents:\\
\\
Scripts:\\
\\
${Selected_Baseline}_compliance.sh \\
\\
This is an interactive shell script to check and/or fix compliance. When run, it can interactively walk the admin through setting co figuration, and outputs results as a log and plist.\\
Usage Example: \\
	sudo ./${Selected_Baseline}_compliance.sh\\
\\
Then choose 1-4 in the interactive script, based on actions provided.\\
\\
This script can also be run with flags or from an MDM. Check (audit) compliance by running the following command with the --check flag.\\
Usage Example: sudo ./${Selected_Baseline}_compliance.sh --check or --fix or --fix --check\\
	--check - will audit the baseline rules\\
	--fix - will audit and remediate the baseline rules\\
\\
Compliance results will be written to:\\
	/Library/Logs/${Selected_Baseline}_baseline.log \\
	/Library/Preferences/org.${Selected_Baseline}.plist\\
\\
_______________\\
\\
xml:\\
\\
The following xml files can be uploaded into Jamf as extension attributes.\\
\\
compliance-exemptions.xml\\
\\
	Displays the exemptions version being used.\\
\\
compliance-FailedResultsCount.xml\\
\\
	Displays the number of compliance controls that failed.\\
\\
compliance-FailedResultsList.xml\\
\\
	Displays the list of compliance controls that failed.\\
\\
compliance-version.xml\\
\\
	Displays the baseline version being used.\\
\\
shell:\\
\\
The following shell scripts can be utilized in other MDMs for inverntory such as Workspace ONE sensors or custom attributes.\\
\\
	compliance-exemptions.sh\\
\\
	Displays the exemptions version being used.\\
\\
compliance-FailedResultsCount.sh\\
\\
	Displays the number of compliance controls that failed.\\
\\
compliance-FailedResultsList.sh\\
\\
	Displays the list of compliance controls that failed.\\
\\
compliance-version.sh\\
\\
	Displays the baseline version being used.\\
\\
_______________\\
\\
Documentation:\\
\\
	${Selected_Baseline}.adoc\\
	${Selected_Baseline}.html\\
	${Selected_Baseline}.pdf\\
\\
The baseline documentation is provided in ASCIIdoc, html, and pdf formats. If a baseline or rule was customized using the project instructions, documentation has been generated that includes these customizations. If rules were customized using the custom directory, .xls auditor guide will identify what customizations were implemented.\\
\\
	${Selected_Baseline}.xls\\
\\
An Auditor Guide is created in .xls format. This file enables an auditor to spot check controls and identify any customizations of rules.\\
\\
_______________\\
\\
mobilleconfig directory:\\
\\
.plist files may be imported into an MDM as custom configuration profiles to enforce baseline rules.\\
\\
.mobileconfig files may also be imported into an MDM or be manually installed on an unmanaged stand alone Mac system if an MDM is not available.\\
\\
_______________\\
\\
preferences directory:\\
\\
${Selected_Baseline}.audit.plist can be used to set an exemption to rules that users in your organization have approval for, so compliance checks can succeed without findings. It can either exist in /Library/Preferences/${Selected_Baseline}.audit.plist or applied via a custom configuration profile.\\
\\
For more details see: {\field{\*\fldinst{HYPERLINK "https://github.com/usnistgov/macos_security/wiki/Compliance-Script"}}{\fldrslt https://github.com/usnistgov/macos_security/wiki/Compliance-Script}}\\
}
ReadMe_mSCP
#
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Validate Project ###
function validate_Project () {

/usr/bin/clear

/usr/bin/printf "REFRESH\n"

/bin/echo "${FUNCNAME[0]}"

if [[ "${sw_build}" -lt 19 ]]; then
	/bin/echo "macOS ${sw_vers_Full} detected. This script requires 10.15 or greater. Exiting now."
	Quit_Project
fi

admincheck

usercheck

Show_ReadMe

# Check if any Apple software updates are available
LastRecommendedUpdatesAvailable=$(/usr/bin/defaults read /Library/Preferences/com.apple.SoftwareUpdate.plist LastRecommendedUpdatesAvailable 2> /dev/null)
if [[ "${LastRecommendedUpdatesAvailable}" -gt 0 ]] && [[ "${CurrentDay}" != "${SoftwareUpdate_Deferred_Date}" ]]  ; then
	/bin/echo "Apple software updates are available."
	Check_for_softwareupdates
fi

Install_Xcode_command_line_tools_via_command_line

Validate_Python

}
###
#

#
### Run Project ###
function run_Project () {

/usr/bin/clear

/usr/bin/printf "REFRESH\n"

/bin/echo "${FUNCNAME[0]}"

New_or_Existing_Project

if [[ "${new_or_existing}" == "New" ]] ; then
	/bin/echo "New Project"
	Check_mSCP_git_availability
	Define_Branch
	Define_New_Directory
	Validate_New_Directory
	Download_macos_security_git
	Download_and_install_macos_security_pip3
	Proceed_to_Baselines
elif [[ "${new_or_existing}" == "Existing" ]] ; then
	/bin/echo "Existing Project"
	Define_Existing_Directory
	Validate_Existing_Directory
	Download_and_install_macos_security_pip3
	Select_Baseline
fi

}
###
#

#
### Quit or Run Again ###
function Quit_or_Run_Again () {
Open_app
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${FUNCNAME[0]}"
DisplayDialogMessage="Do you want to quit now or run the utility again?"
/bin/echo "${DisplayDialogMessage}"
title="Quit or Run Again"
button1="Quit"
button2="Run Again"
DisplayDialogButtonReturned=$(/usr/bin/osascript -e "button returned of (display dialog \"${DisplayDialogMessage}\" with title \"${title}\" buttons {\"${button1}\",\"${button2}\"})")
/usr/bin/clear
/usr/bin/printf "REFRESH\n"
/bin/echo "${DisplayDialogButtonReturned}"
if [[ "${DisplayDialogButtonReturned}" == "${button1}" ]] ; then
	# Quit
	DisplayDialogMessage=""
	Quit_Project
elif [[ "${DisplayDialogButtonReturned}" == "${button2}" ]] ; then
	# Run Again
	DisplayDialogMessage=""
	run_Project
fi
# /bin/echo "End ${FUNCNAME[0]}"
/bin/echo ""
}
###
#

#
### Quit Project ###
function Quit_Project () {
/bin/echo "${FUNCNAME[0]}"
unset UserPassword
/usr/bin/printf "QUITAPP\n"
exit 0
}
###
#

####################################################################################################
# 
# SCRIPT CONTENTS
#
####################################################################################################

validate_Project

run_Project

Quit_Project

exit 0
###############################################################################
